package com.santidev.proyectodante.Manager;


import com.santidev.proyectodante.R;

public class PalabraPlayManager {

    public static int[] setImagenes(){
        int[] idImagenes = new int[81];
        idImagenes[0] = (R.drawable.aejarbol);
        idImagenes[1] = (R.drawable.aejabeja);
        idImagenes[2] = (R.drawable.aejagua);
        idImagenes[3] = (R.drawable.bejbarco);
        idImagenes[4] = (R.drawable.bejballena);
        idImagenes[5] = (R.drawable.bejbicicleta);
        idImagenes[6] = (R.drawable.cejcasa);
        idImagenes[7] = (R.drawable.cejcaramelo);
        idImagenes[8] = (R.drawable.cejcastillo);
        idImagenes[9] = (R.drawable.dejdado);
        idImagenes[10] = (R.drawable.dejdelfin);
        idImagenes[11] = (R.drawable.dejdinosaurio);
        idImagenes[12] = (R.drawable.eejelefante);
        idImagenes[13] = (R.drawable.eejestrella);
        idImagenes[14] = (R.drawable.eejescalera);
        idImagenes[15] = (R.drawable.fejfantasma);
        idImagenes[16] = (R.drawable.fejflor);
        idImagenes[17] = (R.drawable.imagenfoca);
        idImagenes[18] = (R.drawable.gejgato);
        idImagenes[19] = (R.drawable.gejgallina);
        idImagenes[20] = (R.drawable.gejglobo);
        idImagenes[21] = (R.drawable.hejhamburguesa);
        idImagenes[22] = (R.drawable.hejhelado);
        idImagenes[23] = (R.drawable.hejhelicoptero);
        idImagenes[24] = (R.drawable.iejindio);
        idImagenes[25] = (R.drawable.iejisla);
        idImagenes[26] = (R.drawable.iejiglu);
        idImagenes[27] = (R.drawable.jejjirafa);
        idImagenes[28] = (R.drawable.jejjugo);
        idImagenes[29] = (R.drawable.jejjuguete);
        idImagenes[30] = (R.drawable.kejkiwi);
        idImagenes[31] = (R.drawable.kejkoala);
        idImagenes[32] = (R.drawable.kejketchup);
        idImagenes[33] = (R.drawable.lejleche);
        idImagenes[34] = (R.drawable.lejleon);
        idImagenes[35] = (R.drawable.lejlibro);
        idImagenes[36] = (R.drawable.mejmanzana);
        idImagenes[37] = (R.drawable.mejmapa);
        idImagenes[38] = (R.drawable.mejmesa);
        idImagenes[39] = (R.drawable.nejnaranja);
        idImagenes[40] = (R.drawable.nejninioyninia);
        idImagenes[41] = (R.drawable.nejnieve);
        idImagenes[42] = (R.drawable.enejnandu);
        idImagenes[43] = (R.drawable.eneejnoquis);
        idImagenes[44] = (R.drawable.eneejarana);
        idImagenes[45] = (R.drawable.oejoso);
        idImagenes[46] = (R.drawable.oejoreja);
        idImagenes[47] = (R.drawable.oejoveja);
        idImagenes[48] = (R.drawable.pejpera);
        idImagenes[49] = (R.drawable.pejpez);
        idImagenes[50] = (R.drawable.pejpelota);
        idImagenes[51] = (R.drawable.qejqueso);
        idImagenes[52] = (R.drawable.qejquimica);
        idImagenes[53] = (R.drawable.qejquesadilla);
        idImagenes[54] = (R.drawable.rejrana);
        idImagenes[55] = (R.drawable.rejrio);
        idImagenes[56] = (R.drawable.rejrueda);
        idImagenes[57] = (R.drawable.sejsandia);
        idImagenes[58] = (R.drawable.sejserpiente);
        idImagenes[59] = (R.drawable.sejsol);
        idImagenes[60] = (R.drawable.tejtaza);
        idImagenes[61] = (R.drawable.tejtigre);
        idImagenes[62] = (R.drawable.tejtitere);
        idImagenes[63] = (R.drawable.uejuna);
        idImagenes[64] = (R.drawable.uejuva);
        idImagenes[65] = (R.drawable.uejunicornio);
        idImagenes[66] = (R.drawable.vejvaca);
        idImagenes[67] = (R.drawable.vejvela);
        idImagenes[68] = (R.drawable.vejvolcan);
        idImagenes[69] = (R.drawable.wejwaterpolo);
        idImagenes[70] = (R.drawable.wejwaffle);
        idImagenes[71] = (R.drawable.wejwifi);
        idImagenes[72] = (R.drawable.xejxilofono);
        idImagenes[73] = (R.drawable.xejtaxi);
        idImagenes[74] = (R.drawable.xejextraterrestre);
        idImagenes[75] = (R.drawable.yejyoyo);
        idImagenes[76] = (R.drawable.yejyogurt);
        idImagenes[77] = (R.drawable.yejyoga);
        idImagenes[78] = (R.drawable.zejzapato);
        idImagenes[79] = (R.drawable.zejzanahoria);
        idImagenes[80] = (R.drawable.zejzorro);

        return idImagenes;
    }
    public static String[] setPalabras(){

        String[] palabras = new String[81];

        palabras[0] = ("Árbol");
        palabras[1] = ("Abeja");
        palabras[2] = ("Agua");
        palabras[3] = ("Barco");
        palabras[4] = ("Ballena");
        palabras[5] = ("Bicicleta");
        palabras[6] = ("Casa");
        palabras[7] = ("Caramelo");
        palabras[8] = ("Castillo");
        palabras[9] = ("Dado");
        palabras[10] = ("Delfín");
        palabras[11] = ("Dinosaurio");
        palabras[12] = ("Elefante");
        palabras[13] = ("Estrella");
        palabras[14] = ("Escalera");
        palabras[15] = ("Fantasma");
        palabras[16] = ("Flor");
        palabras[17] = ("Foca");
        palabras[18] = ("Gato");
        palabras[19] = ("Gallina");
        palabras[20] = ("Globo");
        palabras[21] = ("Hamburguesa");
        palabras[22] = ("Helado");
        palabras[23] = ("Helicóptero");
        palabras[24] = ("Indio");
        palabras[25] = ("Isla");
        palabras[26] = ("Iglú");
        palabras[27] = ("Jirafa");
        palabras[28] = ("Jugo");
        palabras[29] = ("Juguetes");
        palabras[30] = ("Kiwi");
        palabras[31] = ("Koala");
        palabras[32] = ("Ketchup");
        palabras[33] = ("Leche");
        palabras[34] = ("León");
        palabras[35] = ("Libro");
        palabras[36] = ("Manzana");
        palabras[37] = ("Mapa");
        palabras[38] = ("Mesa");
        palabras[39] = ("Naranja");
        palabras[40] = ("Niño y Niña");
        palabras[41] = ("Nieve");
        palabras[42] = ("Ñandú");
        palabras[43] = ("Ñoquis");
        palabras[44] = ("Araña");
        palabras[45] = ("Oso");
        palabras[46] = ("Oreja");
        palabras[47] = ("Oveja");
        palabras[48] = ("Pera");
        palabras[49] = ("Pez");
        palabras[50] = ("Pelota");
        palabras[51] = ("Queso");
        palabras[52] = ("Quimica");
        palabras[53] = ("Quesadilla");
        palabras[54] = ("Rana");
        palabras[55] = ("Río");
        palabras[56] = ("Rueda");
        palabras[57] = ("Sandia");
        palabras[58] = ("Serpiente");
        palabras[59] = ("Sol");
        palabras[60] = ("Taza");
        palabras[61] = ("Tigre");
        palabras[62] = ("Títere");
        palabras[63] = ("Uña");
        palabras[64] = ("Uva");
        palabras[65] = ("Unicornio");
        palabras[66] = ("Vaca");
        palabras[67] = ("Vela");
        palabras[68] = ("Volcán");
        palabras[69] = ("Waterpolo");
        palabras[70] = ("Waffle");
        palabras[71] = ("Wi-Fi");
        palabras[72] = ("Xilófono");
        palabras[73] = ("Taxi");
        palabras[74] = ("Extraterrestre");
        palabras[75] = ("Yoyo");
        palabras[76] = ("Yogurt");
        palabras[77] = ("Yoga");
        palabras[78] = ("Zapatos");
        palabras[79] = ("Zanahoria");
        palabras[80] = ("Zorro");

        return palabras;
    }



}
